// <auto-generated />
using System;
using KPZ_Lab04.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KPZLab04.Migrations
{
    [DbContext(typeof(KpzLab03DbContext))]
    partial class KpzLab03DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KPZ_Lab04.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageEnglish")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMath")
                        .HasColumnType("float");

                    b.Property<double?>("AveragePhilosophy")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Surname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("TId")
                        .HasColumnType("int")
                        .HasColumnName("t_ID");

                    b.HasKey("Id")
                        .HasName("PK_Student_1");

                    b.HasIndex("TId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("KPZ_Lab04.Models.Teacher", b =>
                {
                    b.Property<int>("TId")
                        .HasColumnType("int")
                        .HasColumnName("t_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("Surname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("surname")
                        .IsFixedLength();

                    b.HasKey("TId");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("KPZ_Lab04.Models.Student", b =>
                {
                    b.HasOne("KPZ_Lab04.Models.Teacher", "TIdNavigation")
                        .WithMany("Students")
                        .HasForeignKey("TId")
                        .HasConstraintName("FK_Student_Teacher");

                    b.Navigation("TIdNavigation");
                });

            modelBuilder.Entity("KPZ_Lab04.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
